# Generated by Django 3.1 on 2020-08-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='vtajtxzzis', max_length=50, unique=True, verbose_name='User Name'),
        ),
    ]
