# Generated by Django 3.1 on 2020-08-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20200817_1553'),
        ('users', '0003_auto_20200817_0859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
