# Generated by Django 3.1 on 2020-08-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='codename',
            field=models.CharField(max_length=50, verbose_name='Code Name'),
        ),
    ]
