# Generated by Django 3.1 on 2020-08-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200817_0044'),
        ('lists', '0002_auto_20200817_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='movie_list',
            field=models.ManyToManyField(blank=True, null=True, to='movies.Movie'),
        ),
    ]
