# Generated by Django 3.1 on 2020-08-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200817_0044'),
        ('lists', '0005_auto_20200817_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='movie_list',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
    ]
