# Generated by Django 3.1 on 2020-08-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20200817_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='codename',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code Name'),
        ),
    ]
