# Generated by Django 3.1 on 2020-08-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Movie Id')),
                ('name', models.CharField(max_length=100, verbose_name='Movie Name')),
                ('avg_rating', models.FloatField(verbose_name='Average Rating')),
            ],
        ),
    ]
